name: my workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "PKGVER=$(sed -n "s/version://p" "$1" | xargs)" >> $GITHUB_ENV
      - name: Test
        run: echo $PKGVER
